disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
identifier_name:
  excluded: # excluded via string array
    - id
line_length:
  - 200 # warning
  - 300 # error